version: "3.9"

services:
  face_recognition:
    container_name: face_recognition
    image: face_recognition:latest
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      APP_PORT: 8080
      APP_DEBUG: 'False'
    volumes:
      - ./volumes/images:/app/images